apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHlydHAuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImNtRm9kV3hrWlhadmNITXlOakF6UUdkdFlXbHNMbU52YlRwRlpIVnlaV3RvUVNrMUl6WT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
